export enum UserErrors {
	UnknownError = 'An unknown error has occurred',
	UserExistsError = 'User with the given email is already registered',
	UserNotExistsError = 'User not exist',
	MissingUsernameError = 'No username was given',
	IncorrectUsernameError = 'The specified user does not exist.',
	MissingPasswordError = 'No password was given',
	IncorrectPasswordError = 'Incorrect password',
	AttemptTooSoonError = 'Account is currently locked. Try again later',
	TooManyAttemptsError = 'Account locked due to too many failed login attempts',
	NoSaltValueStoredError = 'Authentication not possible. No salt value stored',
	AlreadyLoggedIn = 'You are already logged in. Try to log out first',
	AlreadyLoggedOut = 'You are already logged out',
	NotLoggedInForbidden = 'Access forbidden. You must be logged in',
	RightsForbidden = 'Access denied',
	UsernameIsTooShort = 'Username is too short (minimum is 3 characters)',
	PasswordIsTooShort = 'Password is too short (minimum is 8 characters)',
	PasswordsAreNotEqual = 'Passwords are not equal',
}
